# Generated by Django 4.1.4 on 2023-01-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='100 characters max.', max_digits=5),
        ),
    ]
