# Generated by Django 4.1.4 on 2023-01-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
