# Generated by Django 4.1.4 on 2023-01-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_options_remove_comment_time_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner',
            field=models.ForeignKey(default='John', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
